info:
  # 站点标题
  title: 星苒鸭 · 博客
  # 站点副标题
  subtitle: xingranya · 个人博客与作品集
  # 作者名称
  author: 星苒鸭
  # 站点 URL
  url: https://xingranya.cn
# 基础信息 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# 图片配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/defaults
defaults:
  # 网站图标 Favicon
  favicon: /images/favicon.svg
  # 站点 Logo
  logo: /images/avatar-0.jpg
  # 站点头像
  avatar: /images/avatar-0.jpg
# 图片配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# 颜色配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/colors
colors:
  # 主色
  primary: "#FFC0CB"
  # 辅助色（可选）
  secondary:
  # 默认主题模式初始值（会被系统配色偏好覆盖）
  default_mode: light # light, dark
# 颜色配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# 站点个性化 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/global
global:
  # 自定义全局字体
  fonts:
    # 中文字体
    chinese:
      enable: true # 是否启用自定义标题字体
      family: "'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif" # 字体族
      url: "https://fonts.loli.net/css2?family=Source+Sans+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" # 字体 CSS 链接
    # 英文字体
    english:
      enable: true # 是否启用自定义标题字体
      family: "'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif" # 字体族
      url: "https://fonts.loli.net/css2?family=Source+Sans+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" # 字体 CSS 链接    # 自定义标题字体（导航栏、侧边栏）
    title:
      enable: true # 是否启用自定义标题字体
      family: "'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif" # 字体族
      url: "https://fonts.loli.net/css2?family=Source+Sans+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" # 字体 CSS 链接
  # 内容最大宽度
  content_max_width: 1000px
  # 侧边栏宽度
  sidebar_width: 210px
  # 鼠标悬停效果
  hover:
    shadow: true # 阴影效果
    scale: true # 缩放效果
  # 滚动进度
  scroll_progress:
    bar: true # 进度条
    percentage: false # 百分比
  # 网站计数器
  website_counter:
    url: https://cn.vercount.one/js # 计数器脚本（通常无需修改）
    enable: true # 是否启用
    site_pv: true # 站点 PV
    site_uv: true # 站点 UV
    post_pv: true # 文章 PV
  # 是否启用单页体验（使用 swup，类似 pjax）
  single_page: true
  # 是否启用预加载动画
  preloader:
    enable: true
    custom_message: # 自定义消息，留空则显示站点标题
  # 是否启用 Open Graph
  open_graph:
    enable: true
    image: /images/og.webp  # 默认 og:image
    description: 星苒鸭 xingranya · 个人博客与作品集
  # Google Analytics 分析
  google_analytics:
    enable: false # 是否启用 GA
    id:  # Google Analytics 测量 ID
# 站点个性化 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
    

# FONTAWESOME 字体图标 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/fontawesome
fontawesome: # 专业版 v6.2.1
  # 极细版
  thin: false
  # 细体版
  light: false
  # 双重色版
  duotone: false
  # 锐利实心版
  sharp_solid: true
# FONTAWESOME <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# 首页横幅 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/home/home_banner
home_banner:
  # 是否启用首页横幅
  enable: true
  # 横幅样式
  style: fixed # static 或 fixed
  # 横幅图片
  image: 
    light: https://img1.tucang.cc/api/image/show/dfaec2d2a6c8c70d3cb0df64c4c97b0d # light mode
    dark: https://img1.tucang.cc/api/image/show/ac5fcbc88d41dc84518913b836531768 # dark mode
  # 横幅标题
  title: 星苒鸭 · 博客
  # 横幅副标题
  subtitle:
    text: ["Hi there 👋, I'm xingranya / 星苒鸭", 'A passionate developer from China']
    hitokoto:  # 一言配置
      enable: true # 是否启用一言
      show_author: false # 是否显示作者
      api: https://v1.hitokoto.cn # API 地址，可添加类型
    typing_speed: 100 # 打字速度 (ms)
    backing_speed: 80 # 回退速度 (ms)
    starting_delay: 500 # 开始延迟 (ms)
    backing_delay: 1500 # 回退延迟 (ms)
    loop: true # 是否循环
    smart_backspace: true # 是否智能回退
  # 横幅文案颜色
  text_color: 
    light: "#1a1a1a" # 亮色模式 - 深色文字
    dark: "#f5f5f5" # 暗色模式 - 浅色文字
  # 文案样式
  text_style: 
    # 标题字号
    title_size: 2.8rem
    # 副标题字号
    subtitle_size: 1.5rem
    # 标题与副标题行高
    line_height: 1.2
  # 横幅自定义字体
  custom_font: 
    # 是否启用
    enable: true
    # 字体族
    family: 
    # 字体 CSS 链接
    url:
  # 横幅社交链接
  social_links:
    # 是否启用
    enable: true
    # 展示样式
    style: default # default, reverse, center
    # 链接
    links:
      github:  https://github.com/xingranya # 你的 GitHub 链接
      instagram: # 你的 Instagram 链接
      zhihu:  # 你的知乎主页
      twitter:  https://x.com/xingranya # 你的 X(Twitter) 链接
      email:  mailto:xingranya@outlook.jp # 你的邮箱
      # ...... # 可继续添加
    # 带二维码抽屉的社交链接
    qrs:
      weixin: https://img1.tucang.cc/api/image/show/673ba553b98bb81251740a53978dd8e5 # 你的微信二维码图片
      # ...... # 可继续添加
# 首页横幅 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# 导航栏 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/home/navbar
navbar:
  # 自动隐藏导航栏
  auto_hide: true
  # 导航栏背景颜色
  color:
    left: "#f78736" # 左侧 
    right: "#367df7"  # 右侧
    transparency: 50 # 透明度 (10-99)
  # 导航栏宽度（通常无需修改）
  width:
    home: 1200px # 首页
    pages: 1000px # 其他页面
  # 链接
  links:
    Home: 
      path: / 
      icon: fa-regular fa-house
    Blog:
      icon: fa-solid fa-blog
      submenus:
        归档: /archives
        标签: /tags/
        分类: /categories/
    Album:
      icon: fa-solid fa-image
      path: /masonry/ 
    Projects: 
      path: /projects/
      icon: fa-solid fa-folder-open
    About: 
      icon: fa-solid fa-circle-info
      submenus:
        关于我: /about
        友链: /links/
        Github: https://github.com/xingranya
  # Navbar search (local search). Requires hexo-generator-searchdb (npm i hexo-generator-searchdb). See https://github.com/theme-next/hexo-generator-searchdb
  search:
    # Whether to enable
    enable: false
    # Preload search data when the page loads
    preload: true
# 导航栏 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# 首页文章设置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/home/home
home:
  # 侧边栏设置
  sidebar:
    enable: true # 是否启用侧边栏
    position: left # 位置：left, right
    first_item: menu # 首项：menu 或 info
    announcement: # 公告
    show_on_mobile: true # 移动端抽屉是否显示
    links:
      Archives: 
        path: /archives 
        icon: fa-regular fa-archive # can be empty
      # Tags: 
      #   path: /tags 
      #   icon: fa-regular fa-tags # can be empty
      # Categories: 
      #   path: /categories 
      #   icon: fa-regular fa-folder # can be empty
      # ...... # you can add more
  # 文章日期格式
  article_date_format: auto # auto, relative, YYYY-MM-DD, YYYY-MM-DD HH:mm:ss 等
  # 文章摘要长度
  excerpt_length: 100 # 最大摘要长度
  # 分类可见性
  categories:
    enable: true  # 是否启用
    limit: 1 # 最多显示数量
  # 标签可见性
  tags:
    enable: true # 是否启用
    limit: 3  # 最多显示数量
# 首页文章设置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# 文章 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/posts/articles
articles:
  # 文章样式设置
  style:
    font_size: 16px # 字号
    line_height: 1.5 # 行高
    image_border_radius: 14px # 图片圆角
    image_alignment: center # 图片对齐：left, center
    image_caption: false # 是否显示图片标题
    link_icon: true # 是否显示链接图标
    delete_mask: false # 为 <del> 添加遮罩，悬停可见
    title_alignment: left # 标题对齐：left, center
    headings_top_spacing: # 各级标题上边距
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  # 字数统计（需要 hexo-wordcount）https://github.com/willin/hexo-wordcount
  word_count:
    enable: true # 是否启用
    count: true # 是否显示总字数
    min2read: true # 是否显示阅读时长
  # 作者标识
  author_label: 
    enable: true # 是否启用
    auto: true # 是否自动添加等级（Lv1/Lv2/...）
    list: []
  # 代码块设置
  code_block:
    copy: true # 是否显示复制按钮
    style: mac # mac | simple
    highlight_theme: # highlight.js 主题
      light: github # 亮色主题
      dark: vs2015 # 暗色主题
    font: # 自定义字体
      enable: false # 是否启用
      family: # 字体族
      url: # 字体 CSS 链接
  # 目录（TOC）设置
  toc:
    enable: true # 是否启用
    max_depth: 3 # 深度
    number: false # 是否自动编号
    expand: true # 是否展开
    init_open: true # 默认展开
  # 版权声明
  copyright:
    enable: true # 是否启用
    default: cc_by_nc_sa # 默认协议：cc_by_nc_sa, cc_by_nd, cc_by_nc, cc_by_sa, cc_by, all_rights_reserved, public_domain
  # 图片懒加载
  lazyload: true
  # Pangu.js（中英文自动加空格）https://github.com/vinta/pangu.js
  pangu_js: false
  # 文章推荐（需要 nodejieba，移植自 volantis）
  recommendation:
    # 是否启用
    enable: false
    # 推荐标题
    title: Recommended Reading
    # 最大数量
    limit: 3
    # 移动端最大数量
    mobile_limit: 2
    # 占位图
    placeholder: /images/wallhaven-wqery6-light.webp
    # 跳过目录
    skip_dirs: []
# 文章 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

effects: 
  particles: true
  cursoreffects: true


# 评论 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/posts/comment
comment:
  # 是否启用评论
  enable: true
  # 评论系统
  system: gitalk # waline, gitalk, twikoo, giscus
  # 系统配置
  config:
    # Waline comment system. See https://waline.js.org/
    waline:
      serverUrl: https://ifpx3kuv.api.lncldglobal.com # Waline 服务地址，例如 https://example.example.com
      lang: zh-CN # Waline 语言，如 zh-CN, en-US
      emoji: [] # Waline 表情
      recaptchaV3Key: # Google reCAPTCHA v3 密钥
      turnstileKey: # Turnstile 密钥
      reaction: true # Waline 表情反馈
    # Gitalk comment system. See https://github.com/gitalk/gitalk
    gitalk:
      clientID: Ov23liYu16nHSE6Qth0E # GitHub Application Client ID
      clientSecret: 93823d44c8948a1894b29110a05d1de4c6cb9968 # GitHub Application Client Secret
      repo: blog-comment # GitHub repository
      owner: xingranya # GitHub repository owner
      proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # GitHub repository proxy
    # Twikoo comment system. See https://twikoo.js.org/
    twikoo:
      version: 1.6.10 # Twikoo 版本，不清楚请勿修改
      server_url: # Twikoo 服务地址，例如 https://example.example.com
      region: # Twikoo 区域，可为空
    # Giscus comment system. See https://giscus.app/
    giscus:
      repo: # GitHub 仓库，例：EvanNotFound/hexo-theme-redefine
      repo_id: # GitHub 仓库 ID
      category: # GitHub 讨论分类
      category_id: # GitHub 讨论分类 ID
      mapping: pathname # 页面唯一标识：pathname, url, title, og:title。启用 PJAX 时勿用 og:title
      strict: 0 # 严格模式：0, 1
      reactions_enabled: 1 # 表情：0, 1
      emit_metadata: 0 # 输出元数据：0, 1
      lang: en # 语言：en, zh-CN, zh-TW
      input_position: bottom # 评论框位置：top, bottom
      loading: lazy # 懒加载
# 评论 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# 页脚 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/footer
footer:
  # 展示网站运行时间
  runtime: true # 是否显示
  # 页脚图标（FontAwesome 代码）
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  # 网站开始时间，格式：YYYY/MM/DD HH:mm:ss
  start: 2025/10/17 11:45:14
  # 站点统计
  statistics: true # 是否显示（文章总数、总字数）
  # 自定义页脚文案
  customize:
  # ICP 备案号：https://beian.miit.gov.cn/
  icp:
    enable: true # Whether to enable
    number: 鄂ICP备2026006203号-1 # ICP record number
    url: https://beian.miit.gov.cn/ # ICP record url
# FOOTER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# 自定义注入 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/inject
inject:
  # 是否启用注入
  enable: false
  # 注入自定义 head HTML
  head: 
    -
    -
  # 注入自定义 footer HTML
  footer:
    -
    -
# 自定义注入 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# 插件 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/plugins
plugins:
  # RSS 订阅（需要 hexo-generator-feed）。https://github.com/hexojs/hexo-generator-feed
  feed:
    enable: false # 是否启用
  # Aplayer 音乐播放器：https://github.com/DIYgod/APlayer
  aplayer:
    enable: true # 是否启用
    type: fixed # fixed, mini
    audios:
      - name: 漆黑的月光 # audio name
        artist: 封茗囧菌 # audio artist
        url: https://music.163.com/song/media/outer/url?id=2107860834.mp3 # audio url
        cover: https://p1.music.126.net/xgz1Z8jfXIY7M9JyHEVR5w==/109951169156480838.jpg?param=240y240 # audio cover url
        lrc: # audio cover lrc
#      - name: # audio name
#        artist: # audio artist
#        url: # audio url
#        cover: # audio cover url
#        lrc: # audio cover lrc
      # .... you can add more audios here
  # Mermaid JS（需要 hexo-filter-mermaid-diagrams）。https://mermaid.js.org/
  mermaid:
    enable: false # 是否启用
    version: "11.4.1" # 默认 v11.4.1
# 插件 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# 页面模板 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/page_templates
page_templates:
  # 友情链接页列数
  friends_column: 3
  # 标签页样式
  tags_style: blur # blur, cloud
# 页面模板 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# CDN >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/cdn
cdn:
  # 是否启用 CDN
  enable: false
  # CDN 提供商
  provider: npmmirror # npmmirror, zstatic, cdnjs, jsdelivr, unpkg, custom
  # 自定义 CDN URL
  # 示例: https://cdn.custom.com/hexo-theme-redefine/${version}/source/${path}
  # 其中 ${path} 必须指向主题的 source 根目录
  custom_url: 
# CDN <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 开发者模式 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/developer
developer:
  # 是否启用开发者模式（仅主题开发者使用，普通用户勿开）
  enable: false
# 开发者模式 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
